name: Full DAST + PenTest Super Pipeline

on:
  push:
    branches: [main]

env:
  DAST_TARGET_URL: https://portal-wbgg.com

jobs:
  security-scan:
    name: DAST + PenTest Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      ######################################
      # 🛡️ Gobuster
      ######################################
     
      # - name: Install Gobuster
      #   run: |
      #     wget https://github.com/OJ/gobuster/releases/download/v3.6.0/gobuster_Linux_x86_64.tar.gz
      #     tar -xzf gobuster_Linux_x86_64.tar.gz
      #     sudo mv gobuster /usr/local/bin/
      
      # - name: Download Better SecLists Wordlist
      #   run: |
      #     mkdir -p wordlists
      #     curl -L https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/directory-list-2.3-medium.txt \
      #       -o wordlists/directory-list-2.3-medium.txt
      
      # - name: Run Gobuster
      #   run: |
      #     gobuster dir -u $DAST_TARGET_URL -w wordlists/directory-list-2.3-medium.txt -o gobuster.txt
      
      # - name: Upload Gobuster Report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gobuster-report
      #     path: gobuster.txt

      ######################################
      # 🛡️ OWASP ZAP
      ######################################

      - name: Create Output Directory
        run: mkdir -p zap_output

      - name: Run ZAP Baseline Scan
        run: |
          docker run --user root \
            -v $(pwd)/zap_output:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t $DAST_TARGET_URL -r zap_report.html -d || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_output/zap_report.html

      ######################################
      # 🔎 Nikto
      ######################################
      
      - name: Run Nikto
        run: |
          docker run --rm --user root gabesullice/nikto -h $DAST_TARGET_URL > nikto-report.txt
      
      - name: Upload Nikto Report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto-report.txt

      ######################################
      # ⚙️ Wapiti
      ######################################
      - name: Install and Run Wapiti
        run: |
          pip install wapiti3
          wapiti -u $DAST_TARGET_URL -o wapiti-report --format html

      - name: Upload Wapiti Report
        uses: actions/upload-artifact@v4
        with:
          name: wapiti-report
          path: wapiti-report/report.html

      ######################################
      # 🧨 XSStrike
      ######################################
      - name: Install and Run XSStrike (demo)
        run: |
          git clone https://github.com/s0md3v/XSStrike.git
          cd XSStrike && pip install -r requirements.txt
          python3 xsstrike.py -u "$DAST_TARGET_URL/search.php?q=test" --crawl --skip --timeout 5 --blind || true

      - name: Upload XSStrike Report (manual logs)
        run: |
          echo "XSStrike doesn't generate structured reports, saving terminal output..."
          cp XSStrike/output.txt xsstrike-output.txt || touch xsstrike-output.txt

      - name: Upload XSStrike Output
        uses: actions/upload-artifact@v4
        with:
          name: xsstrike-report
          path: xsstrike-output.txt

